# Generated by Django 5.0.1 on 2025-11-02 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CohortCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(max_length=20)),
                ('fixed_day', models.IntegerField()),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('theory', 'Theory Room'), ('lab', 'Lab Room')], max_length=10)),
                ('capacity', models.PositiveIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_lab', models.BooleanField(default=False)),
                ('times_needed', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CohortSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.cohortcourse')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('main', 'Main Schedule'), ('electives', 'Electives')], db_index=True, max_length=20)),
                ('input_hash', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('params', models.JSONField(blank=True, null=True)),
                ('created_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['run_type', 'created_at'], name='scheduler_s_run_typ_695a28_idx'), models.Index(fields=['run_type', 'input_hash'], name='scheduler_s_run_typ_c983b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semester')),
            ],
            options={
                'unique_together': {('semester', 'name')},
            },
        ),
        migrations.AddField(
            model_name='cohortcourse',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semester'),
        ),
        migrations.CreateModel(
            name='StudentCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.PositiveIntegerField()),
                ('semester', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduler.semester')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.room')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections_count', models.PositiveIntegerField()),
                ('can_use_theory', models.BooleanField(default=True)),
                ('can_use_lab', models.BooleanField(default=False)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduler.subject')),
            ],
        ),
        migrations.AddField(
            model_name='cohortcourse',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.subject'),
        ),
        migrations.CreateModel(
            name='ElectiveSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.electiveconfig')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.room')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='cohortcourse',
            name='fixed_timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.timeslot'),
        ),
        migrations.CreateModel(
            name='SectionSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.subject')),
            ],
            options={
                'unique_together': {('section', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.subject')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.timeslot')),
            ],
            options={
                'unique_together': {('room', 'timeslot')},
            },
        ),
    ]
